### ISSUE TITLE
Reorganize repository structure

### ISSUE THREAD

**Issue by rnestler** [LibrePCB/librepcb-parts-generator#65]
Currently the repository contains almost everything in top level. Would it make sense to add directories for the UUID caches for example?

**Comment by dbrgn** [comment]
Yeah, probably wouldn't hurt!

**Comment by ouabache** [comment]
Ok, Here's my proposal.

Keep all python at the top level.

Each Library on the librePCB server gets it's own directory for uuid_caches and run scripts

We need to get to the point where we can automatically regenerate all of our libraries from scripts using the lower level python code.

**Comment by ouabache** [comment]
I tried setting up a directory for the Base library and ran into some issues.

The generate_chips.py is old. It generates version 0.3 while 0.3.2 is checked in

the chip and so scripts have round off errors. The checked in versions have Y positions to 2 digits but I am generating 3. I am running python3.7

**Comment by dbrgn** [comment]
> The generate_chips.py is old. It generates version 0.3 while 0.3.2 is checked in

Ah, #64 wasn't merged yet even though the library PR was already merged.

You can pull master, should be fixed.

**Comment by ouabache** [comment]
Thank you.

I am now going to fix the problem with the names for the DIP packages

**Comment by ouabache** [comment]
Still not right.

There are 11 devices with version 0.3 when the script calls out 0.3.2

Everything else synced up

**Comment by ouabache** [comment]
The generate_so.py script doesn't match the checked in code. In some cases there are different create_dates and the number of places returned by the get_y function varies between 2 or 3

**Comment by dbrgn** [comment]
I'll check it out.

**Comment by dbrgn** [comment]
> There are 11 devices with version 0.3 when the script calls out 0.3.2

This is fixed in master.

> The generate_so.py script doesn't match the checked in code. In some cases there are different create_dates and the number of places returned by the get_y function varies between 2 or 3

I added commit 5db97430e116ea36aac331646b287daab2ee3fe1 when generating the SSOP packages, but then did not re-generate the SOIC packages. I fixed that in PR https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/pull/57.

**Comment by z3ugma** [comment]
@dbrgn, I'm currently integrating `librepcb-parts-generator` as a dependency into another Python project. To facilitate development, my goal was to install it as a package using the standard command `pip install` (or the `uv` equivalent). 

`uv add git+https://github.com/LibrePCB/librepcb-parts-generator.git`

When doing so, I encountered a persistent `ModuleNotFoundError` because the Python import system could not find the `librepcb_parts_generator` package, even though it was correctly listed by the package manager.

**The Root Cause**

The issue stems from a mismatch between the package name and the repository's directory structure. Modern packaging tools expect the importable source code to reside in a subdirectory that matches the package name. For an import like `from librepcb_parts_generator.entities import ...`, the tooling expects a file path similar to this:

`/path/to/project/librepcb_parts_generator/entities/__init__.py`

However, in the current repository layout, the importable modules (such as `common.py` and the `entities` directory) are located at the top level, not within a subdirectory named `librepcb_parts_generator`. Because of this, the Python interpreter cannot resolve the package path correctly after an editable installation.

**Recommendation**

For consideration, adopting this package layout in the main repository would make it directly compatible with standard Python packaging workflows -  This would allow other developers to use the project as a dependency, especially the Entities. 

```
├── librepcb_parts_generator/
│   ├── __init__.py
│   ├── cadquery_helpers.py
│   ├── common.py
│   ├── dfn_configs.py
│   └── entities/
│       ├── __init__.py
│       ├── attribute.py
│       ├── common.py
│       ├── component.py
│       ├── device.py
│       ├── helper.py
│       ├── package.py
│       └── symbol.py
├── .gitignore
├── LICENSE
├── README.md
├── pyproject.toml
└── ... (other root-level configuration files)
``` 

Also consider https://stackoverflow.com/questions/761519/is-it-ok-to-use-dashes-in-python-files-when-trying-to-import-them how there should not be dashes/hyphens in Python package names

**Comment by ubruhin** [comment]
Regarding the scripts, maybe I'd even move each generator into its own subdirectory, including its UUID cache:

```
├── generators
│   ├── dfn
│   │   ├── configs.py
│   │   ├── generate.py
│   │   └── uuids.csv
│   ├── axial_tht
│   │   ├── generate.py
│   │   └── uuids.csv
```

Then everything related is tight together and we can also use shorter filenames. The only drawback I see is that some scripts also access the UUID cache of another generator which then needs to be done with a path leaving the actual script directory (e.g. `../axial_tht/uuids.csv`) but I'd say that's just a minor issue compared to the advantages of the much cleaner directory structure.
